#!/bin/bash

if [ "$#" -lt 2 ]
then
 echo "Usage $0 <parcellate_cfg> <subjid/list>"
 echo ""
 echo "List of standard parcellate_cfgs: "
 pushd $PIPELINE_CFG_DIR/parcellate > /dev/null
 ls *
 popd > /dev/null
 echo ""

 exit 0
fi

  
parcellate_cfg=$PIPELINE_CFG_DIR/parcellate/$1

if [ ! -e $parcellate_cfg ]
then
 echo "tract cfg $parcellate_cfg does not exist!"
 exit 0
fi

echo "Sourcing $parcellate_cfg"
source $parcellate_cfg

shift 1


output_dir=.

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi


for subj in $subjids
do


subj_dir=$output_dir/$subj

 if [ -e $subj_dir/dti/distortCorrect ]
 then  
   dti_dir=$subj_dir/dti/distortCorrect
 else
 
  if [ -e $subj_dir/dti/eddyCorrect ]
  then
    dti_dir=$subj_dir/dti/eddyCorrect 
  else
   echo "Eddy corrected or Distortion corrected DTI data does not exist for $subj"
   continue
  fi
 fi

 bedpost_dir=$dti_dir/bedpost.bedpostX

 #config file specifies: 
   #parcellation_name
   #seed_file
   #target_seg
   #target_mapping_txt
   #target_labels_txt


 seed_file=$subj_dir/$seed_file
 target_seg=$subj_dir/$target_seg

 parc_dir=$dti_dir/bedpost.$parcellation_name
 mkdir -p $parc_dir

 #probtrack output dir
 output_dir=$parc_dir/probtrack

 targets_dir=$parc_dir/targets 
 mkdir -p $targets_dir

 #process for targets
 runMatlabCmd remapSegmentationLabels "'$target_seg'" "'$target_mapping_txt'" "'$target_labels_txt'" "'$targets_dir'"
 
 targets_file=$parc_dir/targets.txt
 ls $targets_dir/*.nii.gz > $targets_file


 #--targetmasks targets_file (txt file, each line nii.gz)

 mask_file=$bedpost_dir/nodif_brain_mask.nii.gz
 
 samples_base=$bedpost_dir/merged

 probtrack_opts="-l --onewaycondition -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --os2t"


 echo probtrackx2 -x $seed_file --targetmasks=$targets_file -m $mask_file -s $samples_base --dir=$output_dir $probtrack_opts
# probtrackx2 -x $seed_file --targetmasks=$targets_file -m $mask_file -s $samples_base --dir=$output_dir $probtrack_opts



#/usr/share/fsl/5.0/bin/probtrackx2 -x /eq-nas/alik/EpilepsyDatabase/standard/projects/epilepsy_peters/EPI_V065/dti/distortCorrect/connParc/L_caudate.nii.gz -l --onewaycondition -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd -s /eq-nas/alik/EpilepsyDatabase/standard/projects/epilepsy_peters/EPI_V065/dti/distortCorrect/bedpost.bedpostX/merged -m /eq-nas/alik/EpilepsyDatabase/standard/projects/epilepsy_peters/EPI_V065/dti/distortCorrect/bedpost.bedpostX/nodif_brain_mask --dir=/eq-nas/alik/EpilepsyDatabase/standard/projects/epilepsy_peters/EPI_V065/dti/distortCorrect/bedpost.bedpostX/testtrack_targetted --targetmasks=/eq-nas/alik/EpilepsyDatabase/standard/projects/epilepsy_peters/EPI_V065/dti/distortCorrect/bedpost.bedpostX/testtrack_targetted/targets.txt --os2t 




done #subj

