#!/bin/bash

if [ "$#" -lt 1 ]
then
 echo "Usage $0 <subjid/list> <opts>"
 echo "  -l <lmax>  : default 6"
 exit 0
fi

output_dir=.

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi

shift 1

while getopts "l:" options; do
 case $options in
    l ) echo "Using custom lmax=$OPTARG"
       lmax=$OPTARG;;
 esac
done




for subj in $subjids
do


subj_dir=$output_dir/$subj

 if [ -e $subj_dir/dti/distortCorrect ]
 then  
   dti_dir=$subj_dir/dti/distortCorrect
 else
 
  if [ -e $subj_dir/dti/eddyCorrect ]
  then
    dti_dir=$subj_dir/dti/eddyCorrect 
  else
   echo "Eddy corrected or Distortion corrected DTI data does not exist for $subj"
   continue
  fi
 fi

 out_dir=$dti_dir/mrtrix

mkdir -p $out_dir

dwi_bvec=$dti_dir/dwi.bvec
dwi_bval=$dti_dir/dwi.bval
dwi_vol=$dti_dir/dwi.nii.gz
brain_mask=$dti_dir/brainmask.nii.gz

nlines=`cat $dwi_bvec | wc -l`

if [ "$nlines" = "3" ]
then
dwi_bvec_t=$dwi_bvec
dwi_bval_t=$dwi_bval
else
dwi_bvec_t=$dti_dir/dwi.bvec_t
dwi_bval_t=$dti_dir/dwi.bval_t
runMatlabCmd transposeBvec "'$dwi_bvec'" "'$dwi_bvec_t'"
runMatlabCmd transposeBvec "'$dwi_bval'" "'$dwi_bval_t'"
fi

dwi=$out_dir/dwi.mif
response=$out_dir/csd_response.txt
fod=$out_dir/fod.mif

echo mrconvert -fslgrad $dwi_bvec_t $dwi_bval_t $dwi_vol $dwi
mrconvert -fslgrad $dwi_bvec_t $dwi_bval_t $dwi_vol $dwi
echo dwi2response $dwi $response -mask $brain_mask -lmax $lmax
dwi2response $dwi $response -mask $brain_mask -lmax $lmax
echo dwi2fod $dwi $response $fod -mask $brain_mask -lmax $lmax
dwi2fod $dwi $response $fod -mask $brain_mask -lmax $lmax


done #subj


