#!/bin/bash

function usage {
 echo ""
 echo "Usage: ${0##*/} <img_type_1> <img_type_2> <label_type> <subjid/list> <options>"
 echo "   -o output_dir  Set output directory (default .)"
 echo "   -S             Use spline interpolation (default nearest neighbour)"
 echo "   -L             Use linear interpolation (default nearest neighbour)"
 echo "" 
 echo " e.g. to propagate t1 maxprob labels to dti for test_subj use:"
 echo "  $0 t1 dti maxprob test_subj"

}

. functions_checkargs

if [ "$#" -lt 4 ]
then
 usage
 exit 0
fi

reg_type=bspline_f3d

output_dir=.

img_type_1=$1 #e.g.: t1, dti, fmri
img_type_2=$2
label_type=$3 #e.g: wm_bundles

shift 3

checkCoregArgs

checkRegArgs

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi

shift 1

interp_opt="-NN 0"
#flag o with argument "o:"
while getopts "o:SL" options; do
 case $options in
    o ) echo "Using output directory: $OPTARG"
        output_dir=$OPTARG;;
    S ) echo "Using spline interpolation"
        interp_opt="";; #cubic spline by default
    L ) echo "Using linear interpolation"
        interp_opt="-LIN";;
    * ) usage
        exit 0;;
 esac
done



for subj in $subjids
do

 subj_dir=$output_dir/$subj
 subj_nii=$subj_dir/$img_path_2
 echo "subj_nii=$subj_nii"
 atlas_label_dir=./${subj}/labels/${img_type_1}/${label_type}


 reg_dir=$subj_dir/reg/${reg_type}_${img_type_1}_${img_type_2}

 out_dir=$subj_dir/labels/${img_type_2}/${label_type}_${reg_type}_${img_type_1}_to_${img_type_2}
 mkdir -p $out_dir

 cpp=$reg_dir/ctrlpt_${img_type_1}_to_${img_type_2}.nii.gz

 if [ ! -e $cpp ]
 then
  echo "Error on $img_type_1 to $img_type_2: Need to run reg_intrasubj_bspline_f3d before propLabels_intrasubj_bspline_f3d!"
  continue
 fi


 for in_label in `ls $atlas_label_dir/*.nii.gz`
 do
  prefix=${in_label##*/}
  prefix=${prefix%%.nii.gz}
  out_label=$out_dir/$prefix.nii.gz
  reg_resample -flo $in_label -res $out_label -cpp $cpp -ref $subj_nii $interp_opt
 done

done
