#!/bin/bash

if [ "$#" -lt 3 ]
then
 echo ""
 echo "Usage: ${0##*/} <mclddmm_cfg> <atlas_subj> <subjid/list>"
 echo ""
 echo "List of standard mcLDDMM_cfgs: "
 pushd $PIPELINE_CFG_DIR/mcLDDMM > /dev/null
 ls *
 popd > /dev/null
 echo ""
 
 exit 0
fi


output_dir=.

chan_cfg=$1
atlas_subj=$2


chan_cfg=$PIPELINE_CFG_DIR/mcLDDMM/$1
cfg_name=${chan_cfg%%.cfg}
cfg_name=${cfg_name##*/}

if [ ! -e $chan_cfg ]
then
 echo "chan cfg $chan_cfg does not exist!"
 exit 0
fi


shift 1

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi


for subj in $subjids
do




if [  "$subj" = "$atlas_subj" ]
then

# look for atlas_subj in current project folder, then in atlas_dir
#  if cannot find in either, then exit

if [  -e $output_dir/$atlas_subj ]
then

  subj_dir=$output_dir/$subj

 else

  #check atlas folder
  if [ -e $PIPELINE_ATLAS_DIR/$atlas_subj ]
  then
    subj_dir=$PIPELINE_ATLAS_DIR/$subj
  else
    echo "atlas: $atlas_subj does not exist!"
    exit 0
  fi

fi


#atlas here:
 atlas_dir=$subj_dir
 atlas_ref=$subj_dir/t1/t1.brain.nii.gz

 if [ -e $subj_dir/dti/distortCorrect ]
 then  
   dti_dir=$subj_dir/dti/distortCorrect
 else
 
  if [ -e $subj_dir/dti/eddyCorrect ]
  then
    dti_dir=$subj_dir/dti/eddyCorrect 
  else
   echo "Eddy corrected or Distortion corrected DTI data does not exist for $subj"
   continue
  fi
 fi
 atlas_dti_dir=$dti_dir
 atlas_labels=$dti_dir/caminoLabels

if [ ! -e $atlas_labels ]
then 
 echo "$atlas_labels does not exist!"
 exit 0
else 
 continue
fi

else
subj_dir=$output_dir/$subj
fi

 if [ -e $subj_dir/dti/distortCorrect ]
 then  
   dti_dir=$subj_dir/dti/distortCorrect
 else
 
  if [ -e $subj_dir/dti/eddyCorrect ]
  then
    dti_dir=$subj_dir/dti/eddyCorrect 
  else
   echo "Eddy corrected or Distortion corrected DTI data does not exist for $subj"
   continue
  fi
 fi

 label_dir=$dti_dir/caminoLabels


 reg_dir=$subj_dir/reg_mcLDDMM_$cfg_name
 ref=$reg_dir/$cfg_name.nii.gz
 map=$reg_dir/reg_$atlas_subj-$subj/lddmm_map.img


for lbl in `ls $atlas_labels/*.nii.gz`
do

 lbl_name=${lbl##*/}
 lbl_name=${lbl_name%%.nii.gz}

 out_dir=$label_dir

 mkdir -p $out_dir

 out_lbl=$out_dir/$lbl_name.nii.gz

 xfm_atlas_dti_t1=$atlas_dti_dir/coreg_T1/xfm/dti-t1.xfm

 #apply dti to t1 xfm in atlas space
 echo reg_resample -flo $lbl -ref $atlas_ref -aff $xfm_atlas_dti_t1 -NN 0 -res $out_lbl
 reg_resample -flo $lbl -ref $atlas_ref -aff $xfm_atlas_dti_t1 -NN 0 -res $out_lbl

 #apply nonrigid warp
 #echo reg_resample -flo $out_lbl -ref $ref -def $map -NN 0 -res $out_lbl
 #reg_resample -flo $out_lbl -ref $ref -def $map -NN 0 -res $out_lbl

 #problem with lddmm_map.img, use Hmap instead for now..
 ana=$out_dir/$lbl_name.temp.img

 affxfm=$reg_dir/reg_$atlas_subj-$subj/mclddmm/regaladin_affine.xfm
 hmap=$reg_dir/reg_$atlas_subj-$subj/mclddmm/Hmap.vtk
 reg_resample -flo $out_lbl -ref $ref -aff $affxfm -NN 0 -res $out_lbl
 mri_convert $out_lbl $ana
 ComposeImageWithMaps $ana $hmap $ana 1
 mri_convert $ana $out_lbl
 
 rm -f $out_dir/$lbl_name.temp.*
 



 dti_ref=$dti_dir/dti_S0.nii.gz 
 xfm_t1_dti=$dti_dir/coreg_T1/xfm/t1-dti.xfm

 #apply t1 to dti xfm in patient space
 echo reg_resample -flo $out_lbl -ref $dti_ref -aff $xfm_t1_dti -res $out_lbl -NN 0
 reg_resample -flo $out_lbl -ref $dti_ref -aff $xfm_t1_dti -res $out_lbl -NN 0


 done #lbl

done #subj


