#!/bin/bash

subjlist=$1

#--------
# Prerequisite: need to import data first
#--------

#importT1 <dicom/nifti>  <subjid>
#importDicomDTI_dcm2nii <dicom folder> <subjid>

for subj in `cat $subjlist`
do


#DTI processing
preprocDTI $subj

#Camino DTI tractography
caminoProcessDTI $subj
caminoTrackingWholeBrainDTI $subj


#constrained spherical deconvolution
# -l 4 option is the Spherical harmonic order and depends on how many gradient directions were acquired
# -> use -l 4 for ~30 directions,  can use -l 6 for 40-60 directions, etc..
mrtrixProcess $subj -l 4
mrtrixTrackingWholeBrainCSDProb $subj 


#T1 and label processing
preprocT1 $subj
reg_intersubj_aladin  t1 MNI152_1mm $subj
reg_bspline_f3d  t1 MNI152_1mm $subj
propLabels_reg_bspline_f3d  t1 HarvardOxford MNI152_1mm $subj

#coregister to dti and propagate labels
reg_intrasubj_aladin  t1 dti $subj -r
propLabels_compose_inter_bspline_intra_aladin t1 t1 dti HarvardOxford MNI152_1mm $subj -r

#generate DTI connectivity
caminoGenConnectivity $subj -L labels/dti/HarvardOxford_bspline_f3d_rigid_aladin_MNI152_1mm/HarvardOxford-combined-maxprob-thr25-1mm.nii.gz -b dti/eddyCorrect/caminoTractographyDTI/wholebrain.Bfloat

#generate CSD connectivity
caminoGenConnectivity $subj -L labels/dti/HarvardOxford_bspline_f3d_rigid_aladin_MNI152_1mm/HarvardOxford-combined-maxprob-thr25-1mm.nii.gz -b dti/eddyCorrect/mrtrixTractographyCSDProb/wholebrain.Bfloat



done

#generate QC
genOverlay_brainmask $subjlist
genOverlay_affine_atlasReg MNI152_1mm $subjlist 
genOverlay_intrasubj t1 dti $subjlist 
genOverlay_bspline_atlasReg MNI152_1mm $subjlist 




