#!/bin/bash


if [ "$#" -lt 1 ]
then
echo "Usage: $0 <install folder (absolute path)>"
exit 0
fi


INSTALL=$1

for script in `ls dependencies/*`
do

. $script $INSTALL

done

INIT=$INSTALL/init.sh

#create init.sh script 

echo "#!/bin/bash" > $INIT
echo "#---- This file is automatically generated by vasst-dev/install_deps.sh ---" >> $INIT
echo "for init in $INSTALL/init.d/*.sh; do . \$init; done" >> $INIT


