#!/bin/bash


## need to update this


if [ "$#" -lt "1" ]
then

echo "Usage: $0 <targetlist> <recon-all options (default -all)>"
exit 0
fi



targetlist=$1

shift 1

if [ "$#" -gt "0" ]
then
 RECON_OPT=$@
else
 RECON_OPT=""
fi



#data_dir=../
data_dir=~/epilepsy/shared_data
out_dir=../
#FS_OPTS="-seg-wlo 100 -seg-ghi 100"


for subj in `cat $targetlist`
do


#original T1w image
#imglbl=origT1w
# in_img=$data_dir/$subj/Preop/Despot/despot1_tr90_fa18.img

#synT1w image (skull-stripped using T1w image
#imglbl=synT1w
#in_img=$data_dir/$subj/Preop/Processed/SynT1weighted/SynT1w_brain.img

#bias-corrected T1w image
imglbl=SynT1w
in_img=$data_dir/$subj/Preop/Processed/SynT1weighted/SynT1w_brain.nii.gz


fsid=Freesurfer_${imglbl}

 subj_dir=$out_dir/$subj/Preop/Processed
 mkdir -p $subj_dir
 
 fs_dir=$subj_dir/$fsid

#import images 
 if [ ! -e $fs_dir/mri/orig/001.mgz ]
 then
   recon-all -sd $subj_dir -i $in_img -subjid $fsid
 fi
 

   recon-all -sd $subj_dir $RECON_OPT -subjid $fsid $FS_OPTS


done
