#!/bin/bash

# dependencies:  unring
# precondition:  importDWI

if [ "$#" -lt 3 ]
then
 echo ""
 echo "Command-line Usage: $0 <in_dwi_folder> <out_dwi_folder> <subjids/list>"
 exit 0
fi

input_dir=$1
output_dir=$2

shift 2


if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$@
fi


for subj in $subjids
do

uncorr_dir=$input_dir/$subj/dwi
unring_dir=$output_dir/$subj/dwi

mkdir -p $unring_dir

for dwi in `ls $uncorr_dir/dwi*.nii.gz`
do

bvec=${dwi%%.nii.gz}.bvec
bval=${dwi%%.nii.gz}.bval
json=${dwi%%.nii.gz}.json

suffix=${dwi##*/}

 unring_dwi=$unring_dir/$suffix
 unring_bvec=${unring_dwi%%.nii.gz}.bvec
 unring_bval=${unring_dwi%%.nii.gz}.bval
 unring_json=${unring_dwi%%.nii.gz}.json

 
  echo unring $dwi $unring_dwi 
  unring $dwi $unring_dwi 


  cp -v $bvec $unring_bvec
  cp -v $bval $unring_bval
  cp -v $json $unring_json
 

done

done
