#!/bin/bash

# dependencies:
#		 mrtrix3 dwidenoise 
# precondition:  importDWI

if [ "$#" -lt 3 ]
then
 echo ""
 echo "Command-line Usage: $0 <in_dwi_folder> <out_dwi_folder> <subjids/list>"
 exit 0
fi

input_dir=$1
output_dir=$2

shift 2


if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$@
fi


for subj in $subjids
do

uncorr_dir=$input_dir/$subj/dwi
denoise_dir=$output_dir/$subj/dwi

mkdir -p $denoise_dir

for dwi in `ls $uncorr_dir/dwi*.nii.gz`
do

bvec=${dwi%%.nii.gz}.bvec
bval=${dwi%%.nii.gz}.bval
json=${dwi%%.nii.gz}.json

suffix=${dwi##*/}

 denoise_dwi=$denoise_dir/$suffix
 denoise_bvec=${denoise_dwi%%.nii.gz}.bvec
 denoise_bval=${denoise_dwi%%.nii.gz}.bval
 denoise_json=${denoise_dwi%%.nii.gz}.json

 
 minvols=10

 nvols=`fslval $dwi dim4`
 if [ "$nvols" -lt "$minvols" ]
 then
  echo "skipping denoise on $denoise_dwi since $nvols is less than minimum $minvols volumes"
  cp -v $dwi $denoise_dwi

  else
 
 echo  dwidenoise $dwi $denoise_dwi -force
  dwidenoise $dwi $denoise_dwi -force


 fi

  cp -v $bvec $denoise_bvec
  cp -v $bval $denoise_bval
  cp -v $json $denoise_json
 

done

done
