#!/bin/bash

#dependencies: fsl (eddy, fslmerge)
#precondition: processTopup

if [ "$#" -lt 2 ]
then
 echo "Writes output to dwi/<in_topup>_eddy"
 echo "Usage $0 <in_uncorrected> <subjid/list>"
 exit 0
fi

output_dir=`pwd`

in_uncorrected=$1
in_topup=${in_uncorrected}_topup
out_name=${in_topup}_eddy
shift 1

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi


for subj in $subjids
do


subj_dir=$output_dir/$subj


uncorr_dir=$subj_dir/dwi/${in_uncorrected}
topup_dir=$subj_dir/dwi/${in_topup}  #change this just to topup and eddy later..
eddy_dir=$subj_dir/dwi/${out_name}


eddy_work=$eddy_dir/work
topup_work=$topup_dir/work

mkdir -p $eddy_dir $eddy_work
#req'd images: dwi_1, dwi_2, hifi, 
brainmask=$topup_dir/brainmask.nii.gz

echo fslmerge  -t  $eddy_work/dwi_uncorrected.nii.gz $uncorr_dir/dwi_?.nii.gz 
fslmerge  -t  $eddy_work/dwi_uncorrected.nii.gz $uncorr_dir/dwi_?.nii.gz 
rm -f $eddy_work/dwi_uncorrected.bval
rm -f $eddy_work/dwi_uncorrected.bvec

#now need to merge bval/bvec
for val in $( for bval in `ls $uncorr_dir/dwi_?.bval`; do cat $bval; done; ) 
do
echo $val >> $eddy_work/dwi_uncorrected.bval
done

for i in `seq 1 3`
do

for vec in  $( for bvec in `ls $uncorr_dir/dwi_?.bvec`; do  cat $bvec | head -n $i | tail -n 1; done; ) 
do
echo -n "$vec " >> $eddy_work/dwi_uncorrected.bvec
done
echo "" >> $eddy_work/dwi_uncorrected.bvec

done


N=`fslval $uncorr_dir/dwi_1.nii.gz dim4`

indx=""; for i in `seq 1 $N`; do indx="$indx 1"; done; for i in `seq 1 $N`; do indx="$indx 2"; done; echo $indx > $eddy_work/index.txt
echo eddy --imain=$eddy_work/dwi_uncorrected --mask=$brainmask --acqp=$topup_work/pedir.txt --index=$eddy_work/index.txt --bvecs=$eddy_work/dwi_uncorrected.bvec --bvals=$eddy_work/dwi_uncorrected.bval --topup=$topup_work/topup --out=$eddy_dir/dwi -v
eddy --imain=$eddy_work/dwi_uncorrected --mask=$brainmask --acqp=$topup_work/pedir.txt --index=$eddy_work/index.txt --bvecs=$eddy_work/dwi_uncorrected.bvec --bvals=$eddy_work/dwi_uncorrected.bval --topup=$topup_work/topup --out=$eddy_dir/dwi -v

dwi_bvec=$eddy_dir/dwi.eddy_rotated_bvecs
dwi_bval=$eddy_work/dwi_uncorrected.bval
dwi_vol=$eddy_dir/dwi.nii.gz
brain_mask=$eddy_dir/brainmask.nii.gz

cp -v $dwi_bvec $eddy_dir/dwi.bvec
cp -v $dwi_bval $eddy_dir/dwi.bval


echo dtifit -k $dwi_vol -o $eddy_dir/dwi -m $brain_mask -r $dwi_bvec -b $dwi_bval
dtifit -k $dwi_vol -o $eddy_dir/dwi -m $brain_mask -r $dwi_bvec -b $dwi_bval


done


