#!/bin/bash



if [ "$#" -lt 2 ]
then
 echo "Command-line Usage: $0 <input T1 dicom folder> <subjid>"
 echo ".. running UI import"

 in_dicom_dir=`zenity --file-selection --directory --title="Choose T1 dicom directory to import"`
 subj=`zenity --entry --title="Enter subject ID:" --text="$in_dicom_dir"`

else

in_dicom_dir=$1
subj=$2

fi

output_dir=.




t1_dir=$output_dir/$subj/t1
mkdir -p $t1_dir


tmp_folder=/tmp/$subj.t1
mkdir -p $tmp_folder

dcm2niix -f '%p_%t_%s' -z y -o $tmp_folder $in_dicom_dir

conv=`ls $tmp_folder/*.nii.gz | head -n 1`

fslreorient2std $conv $t1_dir/t1.nii.gz

rm -rf $tmp_folder
