#!/bin/bash

if [ "$#" -lt 3 ]
then
 echo ""
 echo "Warps subject tract probabability maps back to atlas_subj for group comparison"
 echo "Usage: ${0##*/} <mclddmm_cfg> <atlas_subj> <subjid/list>"
 echo ""
 echo "List of standard mcLDDMM_cfgs: "
 pushd $PIPELINE_CFG_DIR/mcLDDMM > /dev/null
 ls *
 popd > /dev/null
 echo ""
 
 exit 0
fi


output_dir=.

chan_cfg=$1
atlas_subj=$2


chan_cfg=$PIPELINE_CFG_DIR/mcLDDMM/$1
cfg_name=${chan_cfg%%.cfg}
cfg_name=${cfg_name##*/}

if [ ! -e $chan_cfg ]
then
 echo "chan cfg $chan_cfg does not exist!"
 exit 0
fi


shift 1



if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi


for subj in $subjids
do



if [  "$subj" = "$atlas_subj" ]
then

# look for atlas_subj in current project folder, then in atlas_dir
#  if cannot find in either, then exit

if [  -e $output_dir/$atlas_subj ]
then

  subj_dir=$output_dir/$subj

 else

  #check atlas folder
  if [ -e $PIPELINE_ATLAS_DIR/$atlas_subj ]
  then
    subj_dir=$PIPELINE_ATLAS_DIR/$subj
  else
    echo "atlas: $atlas_subj does not exist!"
    exit 0
  fi

fi


#atlas here:
 atlas_dir=$subj_dir
 atlas_ref=$subj_dir/t1/t1.brain.nii.gz

 continue

else
subj_dir=$output_dir/$subj
fi

 if [ -e $subj_dir/dti/distortCorrect ]
 then  
   dti_dir=$subj_dir/dti/distortCorrect
 else
 
  if [ -e $subj_dir/dti/eddyCorrect ]
  then
    dti_dir=$subj_dir/dti/eddyCorrect 
  else
   echo "Eddy corrected or Distortion corrected DTI data does not exist for $subj"
   continue
  fi
 fi

 tract_dir=$dti_dir/caminoTractographyDTI


 reg_dir=$subj_dir/reg_mcLDDMM_$cfg_name
 ref=$subj_dir/t1/t1.brain.nii.gz
 lddmm_dir=$reg_dir/reg_$subj-$atlas_subj
 map=$lddmm_dir/lddmm_map.img

 out_dir=$reg_dir/warpedTractographyDTI
 mkdir -p $out_dir

for img in `ls $tract_dir/*acm*.nii.gz`
do

 img_name=${img##*/}
 img_name=${img_name%%.nii.gz}

 out_img=$out_dir/$img_name.nii.gz

 xfm_dti_t1=$dti_dir/coreg_T1/xfm/dti-t1.xfm

 #apply dti to t1 xfm in atlas space
 echo reg_resample -flo $img -ref $ref -aff $xfm_dti_t1 -res $out_img
 reg_resample -flo $img -ref $ref -aff $xfm_dti_t1 -res $out_img


 #apply nonrigid warp
 #echo reg_resample -flo $out_lbl -ref $ref -def $map -NN 0 -res $out_lbl
 #reg_resample -flo $out_lbl -ref $ref -def $map -NN 0 -res $out_lbl

 #problem with lddmm_map.img, use Hmap instead for now..
 ana=$out_dir/$img_name.temp.img

 affxfm=$lddmm_dir/mclddmm/regaladin_affine.xfm
 hmap=$lddmm_dir/mclddmm/Hmap.vtk
 echo reg_resample -flo $out_img -ref $atlas_ref -aff $affxfm -res $out_img
 reg_resample -flo $out_img -ref $atlas_ref -aff $affxfm -res $out_img
 echo mri_convert $out_img $ana
 mri_convert $out_img $ana
 echo ComposeImageWithMaps $ana $hmap $ana 
 ComposeImageWithMaps $ana $hmap $ana 
 echo mri_convert $ana $out_img
 mri_convert $ana $out_img
 
 rm -f $out_dir/$img_name.temp.*
 

 done #img

done #subj


