#!/bin/bash

if [ "$#" -lt 1 ]
then
 echo "Usage $0 <subjid/list>"
 exit 0
fi

output_dir=.

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi


for subj in $subjids
do



subj_dir=$output_dir/$subj

t1_dir=$subj_dir/t1

bet_t1=$t1_dir/t1.brain.nii.gz

seg_dir=$subj_dir/tissue_seg
mkdir -p $seg_dir

#fast seg
#if [ ! -e $seg_dir/t1.brain.fast_seg.nii.gz ]
#then
echo fast -v -p -o $seg_dir/t1.brain.fast $bet_t1
fast -v -p -o $seg_dir/t1.brain.fast $bet_t1
#fi



done
