#!/bin/bash


if [ "$#" -lt 2 ]
then
 echo "Usage: $0 <subj> <structure>" # <session>"
 echo ""
 echo " e.g.:  $0 EPI_P014 Neo" # Post_fix"
 echo ""
 exit
fi

subj=$1
struct=$2


data_dir=/eq-nas/$USER/EpilepsyDatabase/$subj/Processed/Ex-Hist_Reg
mri=`ls $data_dir/*/$struct/3drigid_iter5/reg_ex_mri.nii.gz | head -n 1`
if [ ! -n "$mri" ]
then 
 echo $subj mri does not exist!
 exit 0
fi

session=${mri##*Ex-Hist_Reg/}
session=${session%%/*}


 runMatlabCmd genFinalTransforms "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd transformCoordHistToMRI "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd TransformHistFidstoExNew "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd computeTRExHistNew "'$subj'" "'$struct'" "'$session'"



