#!/bin/bash


if [ "$#" -lt 3 ]
then
 echo "Usage: $0 <out_reg_dir> <subj> <structure>" # <session>"
 echo ""
 echo " e.g.:  $0 ~/EpilepsyDatabase/epilepsyPhase1/Ex-Hist_Reg EPI_P014 Neo" # Post_fix"
 echo ""
 exit
fi

data_dir=$1
subj=$2
struct=$3

mri=`ls $data_dir/$subj/*/$struct/3drigid_iter5/reg_ex_mri.nii.gz | head -n 1`
if [ ! -n "$mri" ]
then 
 echo $subj mri does not exist!
 exit 0
fi

session=${mri##*Ex-Hist_Reg/}
session=${session%%/*}


 runMatlabCmd genFinalTransforms "'$data_dir'" "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd transformCoordHistToMRI "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd TransformHistFidstoExNew "'$subj'" "'$struct'" "'$session'"
# runMatlabCmd computeTRExHistNew "'$subj'" "'$struct'" "'$session'"



