#!/bin/bash


if [ "$#" -lt 4 ]
then
 echo "Usage: $0 <out_reg_dir> <subj> <structure> <histology study (e.g. Histology)>"  #<session>"
 echo ""
 echo " e.g.:  $0 ~/EpilepsyDatabase/epilepsyPhase1/Ex-Hist_Reg EPI_P014 Neo" #Post_fix"
 echo ""
 exit
fi

out_dir=$1
subj=$2
struct=$3
histology_study=$4

mri=`ls $data_dir/$subj/*/$struct/3drigid_iter5/reg_ex_mri.nii.gz | head -n 1
`
if [ ! -n "$mri" ]
then 
 echo $subj mri does not exist!
 exit 0
fi

session=${mri##*$subj/}
session=${session%%/*}

for png_res in 20 #100 20
do

runMatlabCmd genAlignedNiftiRGB "'$out_dir'" "'$subj'" "'$struct'" "'$session'" "$png_res" "'$histology_study'"

done


