#!/bin/bash
if [ "$#" -lt 1 ]
then
  echo "This script must be run by an administrator."
  echo "Usage: $0 <username>" 
  exit 0
fi



newuser=$1

echo user: $newuser

if [ ! -e /home/ROBARTS/$newuser ]
then
  echo "making new home directory for user: $newuser"
  sudo mkhomedir_helper $newuser
fi 


#create folder for petergrp mount
for fs in petergrp EpilepsyDatabase EpilepsyHistology khangrp
do

sudo mkdir -p /eq-nas/$newuser/$fs
echo "//eq-nas.imaging.robarts.ca/$fs /eq-nas/$newuser/$fs cifs username=$newuser,domain=robarts,noauto,user 0 0" | sudo tee --append /etc/fstab

#link to it
sudo ln -s /eq-nas/$newuser/$fs /home/ROBARTS/$newuser/$fs

done

profile=/home/ROBARTS/$newuser/.bashrc

#echo "if [ -f /cluster/software/etc/init.sh ]"  | sudo tee --append $profile
#echo "then" |  sudo tee --append $profile
#echo " . /cluster/software/etc/init.sh"  | sudo tee --append $profile
#echo "fi"  | sudo tee --append $profile

sw_dir=/opt

echo "if [ -f $sw_dir/init.sh ]"  | sudo tee --append $profile
echo "then" |  sudo tee --append $profile
echo " . $sw_dir/init.sh"  | sudo tee --append $profile
echo "fi"  | sudo tee --append $profile

#sudo mkdir -p /home/$newuser/.vnc

sudo cp startup.m /home/ROBARTS/$newuser/startup.m




