#!/bin/bash

. functions_checkargs

if [ "$#" -lt 3 ]
then
 echo ""
 echo "Usage: ${0##*/}  <img_type> <atlas_subj> <subjid/list>"
 echo ""
 echo " e.g. to register t1 catani to test_subj use:"
 echo "  $0 t1 catani test_subj"
 
 exit 0
fi

reg_type=rigid_aladin

output_dir=.

img_type=$1 #e.g.: t1, dti, fmri
atlas_subj=$2

shift 2


checkRegArgs

 atlas_nii=$atlas_dir/$img_path
 echo atlas_nii=$atlas_nii

 if [ ! -e $atlas_nii ]
 then
  echo "$atlas_nii does not exist, exiting!"
  exit 0
 fi
 
if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi


for subj in $subjids
do



 subj_dir=$output_dir/$subj
 subj_nii=$subj_dir/$img_path
 echo "subj_nii=$subj_nii"


 out_dir=$subj_dir/reg/${reg_type}_${img_type}/${atlas_subj}_${subj}
 mkdir -p $out_dir

 reg_subj=$out_dir/${subj}_to_${atlas_subj}.reg.nii.gz
 xfm=$out_dir/${subj}_to_${atlas_subj}.xfm
 inv_xfm=$out_dir/${atlas_subj}_to_${subj}.xfm
 reg_atlas=$out_dir/${atlas_subj}_to_${subj}.reg.nii.gz

 reg_aladin -ref $atlas_nii -flo $subj_nii -aff $xfm -res $reg_subj -rigOnly
 convert_xfm -omat $inv_xfm -inverse $xfm
 reg_resample -flo $atlas_nii -ref $subj_nii -aff $inv_xfm -res $reg_atlas



done




