#!/bin/bash

#run a pipeline job on the cluster
#pipeline jobs take subjids as args

if [ "$#" -lt 4 ]
then 
  echo ""
  echo "Submits jobs for pipeline scripts that require additional arguments (beyond subject ids)."
  echo ""
  echo "Usage: $0 < # of pipeline script arguments>  <name of pipeline script> <pipeline script arguments> <subjids> ..."
  echo ""
  echo " e.g.:  $0 1 caminoTrackProbDTI  lcingulum_standard.cfg \`cat subject_list.txt\`"
  exit 0
fi

output_dir=.

nargs=$1
pipeline_script=$2

shift 2

pipeline_args=""
for i in `seq 1 $nargs`
do
 
 pipeline_args="$pipeline_args $1"
 shift 1

done


#shift $nargs


echo subjects: $@
echo pipeline args: $pipeline_args



for subj in $@
do

pbs_dir=$output_dir/$subj/pbs
mkdir -p $pbs_dir


scriptname=${pipeline_script##*/} #strip leading path
name=$scriptname.$subj
job=$pbs_dir/$name

echo $pipeline_script $pipeline_args $subj > $job

qsub -N $name -w `pwd`/$pbs_dir -d `pwd` -l "walltime=24:00:00"  -l "mem=6gb" $job

done



