#!/bin/bash

if [ "$#" -lt 6 ]
then
 echo "Usage: $0 <data_dir> <structure> <stain> <featuremapdir - e.g.: 100um_FeatureMaps> <hist_feat_name> <mri_name> <subject ids ...>"
 exit 0
fi

data_dir=$1
struct=$2
stain=$3
feat_dir=$4
featname=$5
mriname=$6
shift 6


res_um=${feat_dir%%um*}

for subj in $@
do

mri_linear=$data_dir/$subj/mri_hist_reg_${struct}_${res_um}um/aligned_mri_${res_um}um/mri_aligned_${struct}_linear_${res_um}.nii.gz
hist_linear=$data_dir/$subj/ ...


mri_dir=$data_dir/$subj/mri_${struct}
reg_dir=$data_dir/$subj/mri_hist_reg_${struct}_${res_um}um
ex_mri=$reg_dir/3drigid_iter5/reg_ex_mri.nii.gz 
ref_mri=$reg_dir/3drigid_iter5/reg_ex_mri_${res_um}um.nii.gz 
ref_mri_iso=$reg_dir/3drigid_iter5/reg_ex_mri_${res_um}um_iso.nii.gz 


mri_aligned_dir=$data_dir/$subj/mri_aligned_${struct}_${res_um}um

hist_aligned_dir=$data_dir/$subj/$feat_dir/aligned/${struct}_${stain}



hist_nii=$hist_aligned_dir/${featname}_rigid_${res_um}um.nii.gz
mri_nii=$mri_aligned_dir/${mriname}.nii.gz


if [ ! -e $hist_nii ]
then
 echo "Hist nifti $hist_nii does not exist!"
 continue;
fi

if [ ! -e $mri_nii ]
then
 echo "Ex MRI nifti $mri_nii does not exist!"
 continue;
fi


nreg_dir=$data_dir/$subj/mri_hist_reg_${struct}_${res_um}um_nonrigid_${featname}_${mriname}

hist_def_nii=$hist_aligned_dir/${featname}_deformable_${res_um}um.nii.gz

echo reg_f3d_split2D $mri_nii $hist_nii $hist_def_nii $nreg_dir
reg_f3d_split2D $mri_nii $hist_nii $hist_def_nii $nreg_dir

#for spacing in 0.2 1.0
#do
#
# cd `pwd` 
#thin=$out_dir/${featname}_rigid_100um.${spacing}thick.nii.gz
#
#echo mri_convert $nii $thin -vs 0.1 0.1 $spacing
# mri_convert $nii $thin -vs 0.1 0.1 $spacing
#
# cd `pwd` 
##convert to thin slice 
#runMatlabCmd convertThickSlicesToGaps "'$nii'" "'$thin'" "'$thin'"
#
#done #spacing
# 
#done


done

