#!/bin/bash

if [ "$#" -lt 1 ]
then
 echo "Usage $0 <subjid or list_txt>"
 exit 0
fi

output_dir=.

if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi  


for subj in $subjids
do


subj_dir=$output_dir/$subj

echo $subj
#put pipeline commands here


done


