#!/bin/bash

if [ "$#" -lt 1 ]
then
  echo "Usage: $0 <username>" 
  exit 0
fi

user=$1


#install software
for sw in `cat software_list`
do

 sudo apt-get -y install $sw

done 

#set-up neurodebian repo
wget -O- http://neuro.debian.net/lists/trusty.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
sudo apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9
sudo apt-get -y update


#install neurodebian software

for sw in `cat software_list_neurodebian`
do

 sudo apt-get -y install $sw

done 

#setup nfs
sudo mkdir -p /cluster/software /cluster/users
echo "sleepy:/cluster/software /cluster/software nfs rw,hard,intr 0 0" | sudo tee --append /etc/fstab > /dev/null
echo "sleepy:/cluster/users /cluster/users nfs rw,hard,intr 0 0" | sudo tee --append /etc/fstab > /dev/null

sudo mount /cluster/software 
sudo mount /cluster/users


