#!/bin/bash

if [ "$#" -lt 1 ]
then 
 echo "Usage: $0 <subjids>"
 exit 0 
fi


#runs single subject fMRI analysis for hippocampal connectivity - generating Zstat maps for lhipp and rhipp
# fmri preprocessing, distortion correction, single-subject ICA, propagating freesurfer labels,  hippocampal connectivity, mapping zstats back to T1space


for subj in $@
do


./1.1_runSingleSubjPreStats $subj
./1.2_runDistortCorrect $subj
./1.3_runSingleSubjICA $subj
./2.1_coregFreesurferLabels $subj
./7_runConnectivityFeat $subj
./8_mapZstatToT1 $subj


done
