#!/bin/bash

if [ "$#" -lt 3 ]
then
 echo "Usage $0 <input_nifti> <id> <output_dicom_folder>"
 exit 0
fi

id=$2
nifti2dicom --seriesnumber 1 --studyid $id --patientname $id --patientid $id -a 1 --studyinstanceuid 1 --seriesinstanceuid 1 --inputfile $1 --protocolname T1 --imagetype T1 --outputdirectory $3
