#!/bin/bash

if [ "$#" -lt 2 ]
then
echo "Fixes nifti orientation from Siemen's diffusion data converted with DWIconvert - flips the (3,3) entry of sform/qform - i.e. flip Z)"
echo "Usage: <input_nii> <output_nii>"
exit 0
fi


in=$1
out=$2

sform=`fslorient -getsform $in`

z=`echo $sform | awk -F" " '{print $11}'`

echo "old z: $z"

firstchar=${z:0:1}
if [ "$firstchar" = "-" ]
then
  z=${z#-} #strip off negative sign
else
  z="-$z"  #add negative sign
fi
echo "new z: $z"
newsform="`echo $sform | awk -F" " '{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10}'` $z `echo $sform | awk -F" " '{print $12,$13,$14,$15,$16}'`"
echo old: $sform
echo new: $newsform

cp -v $in $out
fslorient -setsform $newsform $out
fslorient -copysform2qform $out

