#!/bin/bash


if [ "$#" -lt 2 ]
then
  echo "Usage: $0 <input folder> <output folder>"
  exit 0
fi


in=$1

out=$2

mkdir -p $out

#first get prefix
prefix=`ls $in/*.MR.* -1 | head -n 1`
prefix=${prefix##*/}


prefix="`echo $prefix |  awk -F. '{print $1}'`.`echo $prefix |  awk -F. '{print $2}'`.`echo $prefix |  awk -F. '{print $3}'`"



#get list of first image in each series
for first in `ls $in/$prefix.*.0001.*`
do

 series=${first##*$prefix.}
 series=${series%%.*}

 echo $first: $series

 #get series description from first image:
desc=`dcmdump $first | grep SeriesDescription`
desc_strip=${desc##*[}
desc_strip=${desc_strip%%]*}

out_name=${series}_${desc_strip}

 out_dir=$out/$out_name
 mkdir -p $out_dir
 echo "copying series $series to $out_dir"
  cp  $in/$prefix.$series.* $out_dir
 

 
 first_outdir=`ls $out_dir/$prefix.*.0001.* | head -n 1`
 mri_convert $first_outdir $out/$out_name.nii.gz



done
