#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)


maxchar=20

#short output
#for cfg in `ls  $PIPELINE_CFG_DIR/img_types/*`; do echo  ${cfg##*/}; done 

#long output
for cfg in `ls  $PIPELINE_CFG_DIR/img_types/*`; do 

name=${cfg##*/}
value=`cat $cfg`

nchars=`echo $name | wc -m`

if [ "$nchars" -gt $maxchar ]
then
 spacing=1
else
 spacing=$((maxchar-nchars))
fi


echo -n "${bold}${name}"
for i in `seq 1 $spacing`; do echo -n " "; done
echo "${normal}${value}"; 


done
