#!/bin/bash

#run a pipeline job on the cluster
#pipeline jobs take subjids as args

if [ "$#" -lt 2 ]
then 
  echo "Usage: $0 <name of pipeline script>  <subjid/list> <additional arguments ... if any> "
  exit 0
fi

output_dir=.

pipeline_script=$1

shift 1
if [ -f $1 ]
then
 subjids=`cat $1`
else
 subjids=$1
fi

shift 1

add_args=$@



echo ""
echo "Running with the following arguments:"
echo "  Pipeline script:  $pipeline_script"
echo "  Additional arguments: $@"
echo "  Subjects: "
echo "$subjids"
echo ""
echo "If correct, enter y"
read check
if [ ! "$check" = "y" ]
then
  echo "Quitting..."
  exit 0
else
  echo "Running Jobs... (with 30 sec interval between each submission)"

fi

for subj in $subjids
do



pbs_dir=$output_dir/$subj/pbs
mkdir -p $pbs_dir


scriptname=${pipeline_script##*/} #strip leading path
name=$scriptname.$subj
job=$pbs_dir/$name

echo "#!/bin/bash" > $job
echo cd `pwd` >> $job
echo $pipeline_script $add_args $subj >> $job

#echo sbatch -J $name  -D `pwd` --time=72:00:00 --mem=6000 $job
# echo sbatch -J $name  -D `pwd` $job
# sbatch -J $name  -D `pwd` --time=1:00 --mem=1 $job
 echo sbatch -J $name  -D `pwd` --time=36:00:00  --mem=8000 --account=rrg-akhanf $job
 sbatch -J $name  -D `pwd` --time=36:00:00  --mem=8000 --account=rrg-akhanf $job
#wait 30 sec before sending another..
#sleep 1

done



